<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">replaceUrlAddress</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgb3V0IAoKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5n
ZXRDdXJzb3IoKTsKU3RyaW5nIHVybCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vy
c29yLCAidXJsIik7ClN0cmluZyBuZXdBZGRyZXNzID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlw
ZWxpbmVDdXJzb3IsICJuZXdBZGRyZXNzIik7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCmlm
IChuZXdBZGRyZXNzLmNvbnRhaW5zKCI6IikpIHsKCW5ld0FkZHJlc3MgPSBuZXdBZGRyZXNzLnN1
YnN0cmluZygwLCBuZXdBZGRyZXNzLmluZGV4T2YoIjoiKSk7Cn0KCmludCBzdGFydCA9IHVybC5p
bmRleE9mKCIvLyIpOwppbnQgZW5kID0gdXJsLnN1YnN0cmluZyhzdGFydCkuaW5kZXhPZigiOiIp
ICsgc3RhcnQ7CgppZiAoZW5kID09IC0xIHx8IGVuZCA8IHN0YXJ0KSB7CgllbmQgPSB1cmwuc3Vi
c3RyaW5nKHN0YXJ0KzIpLmluZGV4T2YoIi8iKSArIHN0YXJ0ICsgMjsKfQoKU3RyaW5nIG91dCA9
IHVybC5zdWJzdHJpbmcoMCwgc3RhcnQrMikgKyBuZXdBZGRyZXNzICsgdXJsLnN1YnN0cmluZyhl
bmQpOwoKLy8gcGlwZWxpbmUgb3V0CgpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAidXJs
Iiwgb3V0KTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOwoJ</value>
</Values>
