<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getLastRollbackId</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7CklEYXRhW10Jcm9sbGJhY2sgPSBJRGF0YVV0aWwuZ2V0SURhdGFBcnJheShwaXBl
bGluZUN1cnNvciwgInJvbGxiYWNrIik7CgkKLy8gcHJvY2VzcwoKU3RyaW5nIHJvbGxiYWNrSWQg
PSBudWxsOwoKaWYgKCByb2xsYmFjayAhPSBudWxsICYmIHJvbGxiYWNrLmxlbmd0aCA+IDApIHsK
CQoJSURhdGEgbHIgPSByb2xsYmFja1tyb2xsYmFjay5sZW5ndGgtMV07CgkKCUlEYXRhQ3Vyc29y
IGMgPSBsci5nZXRDdXJzb3IoKTsKCXJvbGxiYWNrSWQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGMs
ICJpZCIpOwoJYy5kZXN0cm95KCk7Cn0KCi8vIHBpcGVsaW5lIG91dAoKSURhdGFVdGlsLnB1dChw
aXBlbGluZUN1cnNvciwgInJvbGxiYWNrSWQiLCByb2xsYmFja0lkKTsKcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOw==</value>
</Values>
