<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">makeStringList</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgaW4KCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7ClN0cmluZyBpbiA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZWxpbmVDdXJzb3Is
ICJpbiIpOwoKLy8gcHJvY2VzcwoJCkxpc3Q8U3RyaW5nPiBsaXN0ID0gbmV3IEFycmF5TGlzdDxT
dHJpbmc+KCk7CgppZiAoaW4gIT0gbnVsbCkgewoJaWYgKGluLnN0YXJ0c1dpdGgoIlsiKSkgewoJ
CWluID0gaW4uc3Vic3RyaW5nKDEsIGluLmxlbmd0aCgpLTEpOwoJfQoJCglTdHJpbmdUb2tlbml6
ZXIgdGsgPSBuZXcgU3RyaW5nVG9rZW5pemVyKGluLCAiLCIpOwoJCgl3aGlsZSAodGsuaGFzTW9y
ZVRva2VucygpKSB7CgkJU3RyaW5nIHN0ciA9IHRrLm5leHRUb2tlbigpOwoJCgkJaWYgKHN0ci5z
dGFydHNXaXRoKCJcIiIpIHx8IHN0ci5zdGFydHNXaXRoKCJcJyIpKQoJCQlsaXN0LmFkZChzdHIu
c3Vic3RyaW5nKDEsIHN0ci5sZW5ndGgoKS0xKSk7CgkJZWxzZQoJCQlsaXN0LmFkZChzdHIpOwoJ
fQp9Ci8vIHBpcGVsaW5lIG91dAoKSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImxpc3Qi
LCBsaXN0LnRvQXJyYXkobmV3IFN0cmluZ1tsaXN0LnNpemUoKV0pKTsKcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOw==</value>
</Values>
