<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getLocalVersion</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgdiA9IElEYXRhVXRp
bC5nZXRTdHJpbmcoYywgImFwaVZlcnNpb24iKTsKClN0cmluZyBsdiA9ICIxLjAiOwoKaWYgKHYg
PT0gbnVsbCB8fCB2Lmxlbmd0aCgpID09IDApIHsKCXYgPSBTeXN0ZW0uZ2V0ZW52KCJhcGlfZ2F0
ZXdheV9kZWZhdWx0X3ZlcnNpb24iKTsKCQoJaWYgKHYgIT0gbnVsbCAmJiAhdi5lcXVhbHMoIm51
bGwiKSkgewoJCWx2ID0gdjsKCX0KfSBlbHNlIHsKCWx2ID0gdjsKfQoKaWYgKGx2LmNvbnRhaW5z
KCIuIikpIHsKCWludCBkb3QgPSBsdi5pbmRleE9mKCIuIik7CglTdHJpbmcgbWFqb3IgPSBsdi5z
dWJzdHJpbmcoMCwgZG90KTsKCVN0cmluZyBtaW5vciA9IGx2LnN1YnN0cmluZyhkb3QrMSk7CgkK
CWlmIChtaW5vci5jb250YWlucygiLiIpKSB7CgkJLy8gaWdub3JlIHBhdGNoZXMKCQkKCQltaW5v
ciA9IG1pbm9yLnN1YnN0cmluZygwLCBtaW5vci5pbmRleE9mKCIuIikpOwoJfQoJCglsdiA9IG1h
am9yICsgIi4iICsgbWlub3I7Cn0gZWxzZSB7CglsdiA9IHY7Cn0KCklEYXRhVXRpbC5wdXQoYywg
ImxvY2FsVmVyc2lvbiIsIGx2KTsKYy5kZXN0cm95KCk7Cgk=</value>
</Values>
