<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getAPIs</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgIGluCgoJCi8vIHByb2Nlc3MKCkFQSUluZm9bXSBhcGlzID0gUGFja2FnZUlu
dHJvc3BlY3Rvci5kZWZhdWx0SW5zdGFuY2UoImRlZmF1bHQiLCAiLi9wYWNrYWdlcyIsIG51bGws
IGZhbHNlKS5hcGlzKCk7CgpMaXN0PElEYXRhPiBvdXQgPSBuZXcgQXJyYXlMaXN0PElEYXRhPigp
OwoKZm9yIChBUElJbmZvIGFwaSA6IGFwaXMpIHsKCQoJaWYgKCFhcGkuZ2V0TmFtZSgpLmVxdWFs
cygiVGVzdFJ1bm5lciIpICYmICFhcGkuZ2V0TmFtZSgpLmVxdWFscygidG9vbHMiKSkgewoJCQoJ
CUlEYXRhIGkgPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7CgkJSURhdGFDdXJzb3IgYyA9IGkuZ2V0
Q3Vyc29yKCk7CgkJSURhdGFVdGlsLnB1dChjLCAibmFtZSIsIGFwaS5nZXROYW1lKCkpOwoJCUlE
YXRhVXRpbC5wdXQoYywgImJhc2VQYXRoIiwgYXBpLmdldEJhc2VQYXRoKCkpOwoJCUlEYXRhVXRp
bC5wdXQoYywgInN3YWdnZXIiLCBhcGkuc3dhZ2dlckVuZHBvaW50KCkpOwoJCUlEYXRhVXRpbC5w
dXQoYywgInBhY2thZ2UiLCBhcGkuZ2V0UGFja2FnZU5hbWUoKSk7CgoJCWMuZGVzdHJveSgpOwoJ
CW91dC5hZGQoaSk7Cgl9CgkKfQoKLy8gcGlwZWxpbmUgb3V0CgpJRGF0YUN1cnNvciBjID0gcGlw
ZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhVXRpbC5wdXQoYywgImFwaXMiLCBvdXQudG9BcnJheShu
ZXcgSURhdGFbb3V0LnNpemUoKV0pKTsKCQ==</value>
</Values>
